#create new account
create_account= "link:Create new account"
first_name= "xpath://input[@name='firstname']"
last_name= "xpath://input[@name='lastname']"
reg_email= "xpath://input[@aria-label='Mobile number or email address' ]"
re_reg_email="xpath://input[@name='reg_email_confirmation__']"
password="id:password_step_input"
dob_d=  "id:day"
dob_m=  "id:month"
dob_y=  "id:year"
#gender= "xpath://input[@name='sex']"
sign_up= "xpath://button[@name='websubmit']"
#to login
login_email="id:email"
login_password="id:pass"
login_link="xpath:(//button[normalize-space()='Log in'])[1]"